# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "notify"
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jugyo"]
  s.date = "2013-04-04"
  s.description = "The \"notify\" provides a function to notify on cross platform."
  s.email = "jugyo.org@gmail.com"
  s.executables = ["notify"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/notify",
    "lib/notify.rb",
    "lib/notify/growlnotify.rb",
    "lib/notify/kdialog.rb",
    "lib/notify/libnotify.rb",
    "lib/notify/notify-send.rb",
    "lib/notify/ruby-growl.rb",
    "lib/notify/ruby_gntp.rb",
    "lib/notify/terminal-notifier.rb",
    "notify.gemspec",
    "sample.rb"
  ]
  s.homepage = "http://github.com/jugyo/notify"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.0"
  s.summary = "A function to notify on cross platform."
end

